let countryCodes = {
    "Belgium": "BE",
    "Greece": "GR",
    "Lithuania": "LT",
    "Portugal": "PT",
    "Bulgaria": "BG",
    "Spain": "ES",
    "Luxembourg": "LU",
    "Romania": "RO",
    "Czechia": "CZ",
    "France": "FR",
    "Hungary": "HU",
    "Slovenia": "SI",
    "Denmark": "DK",
    "Croatia": "HR",
    "Malta": "MT",
    "Slovakia": "SK",
    "Germany (until 1990 former territory of the FRG)": "DE",
    "Italy": "IT",
    "Netherlands": "NL",
    "Finland": "FI",
    "Estonia": "EE",
    "Cyprus": "CY",
    "Austria": "AT",
    "Sweden": "SE",
    "Ireland": "IE",
    "Latvia": "LV",
    "Poland": "PL",
    "United Kingdom": "UK",
    "Iceland": "IS",
    "Liechtenstein": "LI",
    "Norway": "NO",
    "Switzerland": "CH",

    "CH": "Switzerland",
    "NO": "Norway",
    "LI": "Liechtenstein",
    "IS": "Iceland",
    "BE": "Belgium",
    "GR": "Greece",
    "LT": "Lithuania",
    "PT": "Portugal",
    "BG": "Bulgaria",
    "ES": "Spain",
    "LU": "Luxembourg",
    "RO": "Romania",
    "CZ": "Czechia",
    "FR": "France",
    "HU": "Hungary",
    "SI": "Slovenia",
    "DK": "Denmark",
    "HR": "Croatia",
    "MT": "Malta",
    "SK": "Slovakia",
    "DE": "Germany (until 1990 former territory of the FRG)",
    "IT": "Italy",
    "NL": "Netherlands",
    "FI": "Finland",
    "EE": "Estonia",
    "CY": "Cyprus",
    "AT": "Austria",
    "SE": "Sweden",
    "IE": "Ireland",
    "LV": "Latvia",
    "PL": "Poland",
    "UK": "United Kingdom"

}